<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="tP2_LOG8430" nsURI="http://www.example.org/tP2_LOG8430" nsPrefix="tP2_LOG8430">
  <eClassifiers xsi:type="ecore:EClass" name="ICommand" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="codeResult" eType="#//CommandCodeResult"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="result" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CommandCodeResult">
    <eLiterals name="SUCCESS"/>
    <eLiterals name="ERROR" value="1"/>
  </eClassifiers>
</ecore:EPackage>
